"""add refresh_token table

Revision ID: 0f8cbd24903b
Revises: 1029be29d0b3
Create Date: 2026-02-23 21:07:39.599364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8cbd24903b'
down_revision: Union[str, Sequence[str], None] = '1029be29d0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transliterations', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('transliterations', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transliterations', 'active')
    op.drop_column('transliterations', 'status')
    # ### end Alembic commands ###
